### ISSUE TITLE
[object Object] returned by deployed function when invoked via curl

### ISSUE THREAD

**Issue by shaunsmith** [fnproject/fdk-node#11]
The current boilerplate generated Node.js example returns `[object Object]` instead of the expected JSON response when called via curl/direct http.  Console output:
```
$ curl http://localhost:8080/r/demo/hello
[object Object]
```
I tried explicitly specifying `Content-Type: application/json` but there was no change. However when I called the function with `fn call` the function returns the expected JSON:
```
$ fn call demo hello
{"message":"Hello World"}
```
The output is essentially the same whether input is provided or not.

Client version:  0.4.66
Server version:  0.3.410
FDK version (in boilerplate package.json): 0.x

**Comment by zootalures** [comment]
This is to do with the request content type i think - will look.

**Comment by zootalures** [comment]
Looks like 0.0.7 with the fix for this wasn't pushed properly due to circle configuration - looking now.

**Comment by zootalures** [comment]
Fixed now that 0.0.7 is merged : 
```
OCliffe@OCLIFFE-mac /t/nodefn> fn deploy --app foo  --local                                                                                                                        1
Deploying nodefn to app: foo at path: /nodefn
Bumped to version 0.0.7
Building image nodefn:0.0.7 .
Updating route /nodefn using image nodefn:0.0.7...
OCliffe@OCLIFFE-mac /t/nodefn> fn call foo nodefn
{"message":"Hello World"}%
```

**Comment by shaunsmith** [comment]
Thanks Owen!

**Comment by zootalures** [comment]
Thanks @treeder  for sorting out the build!

**Comment by zootalures** [comment]
sorry - realise I hadn't tested the actual bug here, that is also fixed: 

```
curl http://localhost:8080/r/foo/nodefn
{"message":"Hello World"}%
```
