### ISSUE TITLE
405Method Not Allowed for all HTTP methods (GET/OPTIONS/PUT/DELETE) except POST

### ISSUE THREAD

**Issue by krishwin** [fnproject/fdk-node#34]
Does  fn support only HTTP POST Method. i am trying to build  a function and call it from a SPA which needs CORS Support and essentially OPTIONS Call . from Post man i keep getting 405Method Not Allowed .

**Comment by zootalures** [comment]
The functions invoke API only supports post , however if you want to front a function with a REST endpoint you should look at HTTP triggers see https://medium.com/fnproject/getting-started-with-fn-project-65c334b0a63f for an example
