### ISSUE TITLE
console.log pollutes stdout 

### ISSUE THREAD

**Issue by zootalures** [fnproject/fdk-node#5]
console.log seems to be directed to stdout by default: 

in a JSON function : 
```
const fdk = require('@fnproject/fdk')

fdk.handle(function (input, ctx) {
	console.log("Running function")
	return "OK"
})
```

causes a JSON parse error in fn: 
```
{"error":{"message":"invalid json response from function err: invalid character 'R' looking for beginning of value"}}
```

`console` is assignable so fix is to replace it with a monkey-patched version that sends logs to stderr only .

**Comment by treeder** [comment]
Or like other languages we should tell people to use `console.error()`. Trying to think whether all the FDK's should redirect stdout to stderr like you're suggesting.... ???

**Comment by zootalures** [comment]
Yeah I think they should (if they can!)

Java does redirect stdout -> stderr  for the same reason (so System.out.printf(..) goes to the function log rather than polluting the call contract) 

Thinking that bugs caused by (e.g) an accidental systemout.print  are going to be very difficult to debug as you'll just see a random Fn error relating to invalid protocols somwhere.

**Comment by shaunsmith** [comment]
There are a number of frameworks that could be used.  I had tried a few but didn't invest enough time to determine if anyone of them was ideal.  Most seem to be focused on unit testing but one might work for us.

**Comment by rkaw92** [comment]
Hi, is this still an issue now that HTTP with UNIX sockets is used for function I/O instead of stdin/stdout?

**Comment by rdallman** [comment]
it is not, thanks!
